### ISSUE TITLE
Horizontal scrolling disabled when ``containerStyle`` prop is set

### ISSUE THREAD

**Issue by camd** [mozilla-frontend-infra/react-lazylog#28]
I had set the ``containerStyle`` prop on ``LazyLog`` to add a little margin at the bottom like so:

    <LazyLog
      containerStyle={{ marginBottom: '3em' }}
    />

And it worked well to add a little extra space at the bottom of the lines, when scrolled all the way to the bottom.  But it disabled horizontal scrolling.  So I had to set it to:

    containerStyle={{ marginBottom: '3em', overflow: 'auto hidden' }}

which worked.  But seems like we shouldn't need to do that.

**Comment by helfi92** [comment]
The default props for `containerStyle` is defined in https://github.com/mozilla-frontend-infra/react-lazylog/blob/49f22dc2d9f7f18b819fb231864a3a75819453e9/src/components/LazyLog/index.jsx#L152-L156

Modifying `containerStyle` would no longer use the default props which is why scrolling doesn't work anymore. I would just do:

```jsx
containerStyle: {
  width: 'auto', 
  maxWidth: 'initial', 
  overflowX: 'scroll',
  marginBottom: '3em',
},
```

```jsx
containerStyle={classes.containerStyle}
```
