### ISSUE TITLE
Lazylog onScroll prop does not exist, makes ScrollFollow useless

### ISSUE THREAD

**Issue by ausrasul** [mozilla-frontend-infra/react-lazylog#40]
According to the documentation, ScrollFollow should be used like this:
```
<ScrollFollow
    startFollowing={true}
    render={({ follow, onScroll }) => (
        <LazyLog url="http://example.log" stream follow={follow} onScroll={onScroll} />
    )}
/>
```

Where onScroll prop of LazyLog should trigger upon user scrolling.
However this prop does not exist either in the code nor documentation of Lazylog component.

This is true even in the [demo and documentation](https://mozilla-frontend-infra.github.io/react-lazylog/#scrollfollow) page:

The "follow" is not stopped when I scroll to the top.

**Comment by helfi92** [comment]
>  However this prop does not exist either in the code nor documentation of Lazylog component.

From https://github.com/mozilla-frontend-infra/react-lazylog#lazylog-:

"In addition to the props listed for LazyLog, most of the properties available to [react-virtualized List](https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md) can be provided and will be passed through to the component"

> The "follow" is not stopped when I scroll to the top.

You would need to set the `follow` prop to `false` if you want to stop following. The demo doesn't add that logic since we would need to probably add another button to re-enable the follow.

Hope that helps.

**Comment by ausrasul** [comment]
> You would need to set the `follow` prop to `false` if you want to stop following. The demo doesn't add that logic since we would need to probably add another button to re-enable the follow.

If I add a logic to set the "follow" prop based on onScroll event, what is the reason to use ScrollFollow component?
I could set the follow prop to the LazyLog component directly.

Am I missing something?

**Comment by helfi92** [comment]
> If I add a logic to set the "follow" prop based on onScroll event, what is the reason to use ScrollFollow component?

ScrollFollow takes care of the `follow` prop for you instead of handling the state on your own.

> This is true even in the demo and documentation page:

> The "follow" is not stopped when I scroll to the top.

Now that I think about it, I think this is a bug in the `ScrollFollow` component :(

**Comment by helfi92** [comment]
I would be happy to accept a PR if you're interested.

**Comment by ausrasul** [comment]
I'll give it a try!

**Comment by ausrasul** [comment]
Ok, a PR is sent.

I also added a feature that resumes following if the user scrolls all the way down and the "startFollowing" prop is set. Just like in a terminal. 
Let me know if you want it removed.

**Comment by helfi92** [comment]
Thanks for the PR :) I will review it as soon as I get a chance. Hope that's ok.

**Comment by descalzi** [comment]
am also interested in this fix when it becomes available. Thx

**Comment by YevhenTarashchyk** [comment]
@ausrasul Hello ) so did u fix that issue ?

**Comment by ausrasul** [comment]
Hello @YevhenTarashchyk !
Yes, it is in PR https://github.com/mozilla-frontend-infra/react-lazylog/pull/41
I probably should rebase and send the PR again though.

**Comment by YevhenTarashchyk** [comment]
@ausrasul It would be nice ) i will really appreciate this, because for me "onScroll" and "stopFollowing" are not working, i don't get why this features are in official documentation and they are not working. Almost two years have passed and no updates xD

**Comment by YevhenTarashchyk** [comment]
@helfi92 could you pls review the pr 
P.S. i don't understand why we need ScrollFollow if it is not working at all

**Comment by bduffany** [comment]
Can confirm that `ScrollFollow` doesn't work at all, because the `render` prop changes every time the `ScrollFollow` component re-renders, since a new lambda gets passed in each time.

This causes `getDerivedStateFromProps` to return `{ follow: this.props.startFollowing }`, forcing the value of `this.state.follow` to always be set to whatever the `startFollowing` prop is set to.

So effectively, the following code:

```tsx
<ScrollFollow
  startFollowing
  render={({ follow, onScroll }) =>  <LazyLog follow={follow} onScroll={onScroll} />}
/>
```
is equivalent to

```tsx
<LazyLog follow={true} />
```

**Comment by melloware** [comment]
This has been fixed in my fork of this library see: https://github.com/melloware/react-logviewer/issues/14
